// Generated from contracts/openapi.json; regenerate with scripts/generate-contract.mjs.
export interface ComputeSchemas {
"PlaceInstantRequest": ({ "utc"?: ComputeSchemas["Instant"]; "local"?: ComputeSchemas["LocalTime"]; "latitude": ComputeSchemas["Latitude"]; "longitude": ComputeSchemas["Longitude"]; "houseSystem"?: ComputeSchemas["HouseSystem"] }) & ({ "utc": unknown; "local"?: never } | { "utc"?: never; "local": unknown });
"Instant": string;
"LocalTime": { "date": string; "time": string; "zone": string };
"Latitude": number;
"Longitude": number;
"HouseSystem": "whole" | "placidus" | "porphyry" | "equal" | "equal-mc" | "vehlow" | "koch" | "regiomontanus" | "campanus" | "topocentric" | "alcabitius" | "morinus" | "meridian";
"ChartResponse": { "schema": "zodiacs.compute-api.chart.v1"; "result": ComputeSchemas["ChartResult"]; "receipt": ComputeSchemas["CalculationReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"ChartResult": { "instant": string; "local": (ComputeSchemas["LocalResolution"] | null); "bodies": Array<ComputeSchemas["BodyPosition"]>; "angles": (ComputeSchemas["Angles"] | null); "houses": (ComputeSchemas["Houses"] | null); "aspects": Array<ComputeSchemas["Aspect"]>; "flags": Array<ComputeSchemas["ChartFlag"]>; "deltaT": ComputeSchemas["DeltaT"]; "timeScale": ComputeSchemas["TimeScale"]; [key: string]: unknown };
"LocalResolution": { "offsetMinutes": number; "flags": Array<"dst-gap" | "dst-fold" | "lmt">; "localMeanTime": ({ "longitude": number; "zoneOffsetMinutes": number; [key: string]: unknown } | null); "zoneHistory": "pinned" | "runtime"; "zoneUncertain": boolean; [key: string]: unknown };
"BodyPosition": { "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto" | "North Node" | "South Node"; "lon": number; "lat": number; "speed": number; "retrograde": boolean; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; [key: string]: unknown };
"Angles": { "asc": number; "mc": number; "dsc": number; "ic": number; [key: string]: unknown };
"Houses": { "system": ComputeSchemas["HouseSystem"]; "cusps": Array<number>; [key: string]: unknown };
"Aspect": { "a": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto" | "North Node" | "South Node"; "b": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto" | "North Node" | "South Node"; "type": "conjunction" | "sextile" | "square" | "trine" | "opposition"; "orb": number; "applying": boolean; [key: string]: unknown };
"ChartFlag": "dst-gap" | "dst-fold" | "lmt" | "no-time" | "polar-fallback" | "outside-reference-span";
"DeltaT": { "seconds": number; "sigma": number; "model": "iers-utc/1" | "zodiacs-deltat/1"; "table": string; "tableDigest": string; "segment": "long-term" | "reconstructed" | "observed" | "predicted" | "extrapolated"; [key: string]: unknown };
"TimeScale": { "input": "utc"; "basis": "iers" | "delta-t"; "ut1MinusUtc": ({ "seconds": number; "sigma": number; "source": "observed" | "predicted" | "fallback"; [key: string]: unknown } | null); "leapSeconds": ({ "taiMinusUtc": number; "listed": boolean; [key: string]: unknown } | null); [key: string]: unknown };
"CalculationReceipt": { "schema": "zodiacs.calculation-receipt.draft-v1"; "instant": string; "sourceInstant"?: (string | null); "timeKnown": boolean; "reference": "supplied-instant" | "utc-noon" | "local-noon"; "localResolution": ({ [key: string]: unknown } | null); "coordinates": ({ "latitude": number; "longitude": number; [key: string]: unknown } | null); "houses": { "requested": unknown; "actual": unknown; "absenceReason": unknown; [key: string]: unknown }; "inputFlags": Array<ComputeSchemas["ChartFlag"]>; "resultFlags": Array<ComputeSchemas["ChartFlag"]>; "engine": ComputeSchemas["Backend"]; "provenance": ({ [key: string]: unknown } | null); "conventions": { [key: string]: string }; "coverage": { [key: string]: string }; [key: string]: unknown };
"Backend": { "name": "@zodiacs/engine"; "version": string; "ephemeris": { "name": "astronomy-engine"; "version": string; [key: string]: unknown }; [key: string]: unknown };
"Cite": { "url": string; "receipt": string; "engine": "@zodiacs/engine"; "version": string };
"ErrorResponse": { "error": { "code": "not-found" | "method-not-allowed" | "disabled" | "rate-limited" | "rate-limit-unavailable" | "unsupported-media-type" | "payload-too-large" | "invalid-json" | "invalid-request" | "budget-exhausted" | "calculation-failed"; "message": string; "pointer"?: string; "limit"?: string; "max"?: number; "retryAfterSeconds"?: number; [key: string]: unknown }; [key: string]: unknown };
"PositionsRequest": { "instants": Array<ComputeSchemas["Instant"]>; "bodies"?: Array<"Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto" | "North Node" | "South Node"> };
"PositionsResponse": { "schema": "zodiacs.compute-api.positions.v1"; "result": ComputeSchemas["PositionsResult"]; "receipt": ComputeSchemas["ComputeReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"PositionsResult": { "instants": Array<{ "instant": string; "bodies": Array<ComputeSchemas["BodyPosition"]>; "deltaT": ComputeSchemas["DeltaT"]; "timeScale": ComputeSchemas["TimeScale"]; "flags": Array<"outside-reference-span">; [key: string]: unknown }>; [key: string]: unknown };
"ComputeReceipt": { "schema": "zodiacs.compute-receipt.v1"; "endpoint": "chart" | "positions" | "houses" | "events" | "time" | "sky-fact" | "elections"; "engine": ComputeSchemas["Backend"]; "conventions": { [key: string]: string }; "coverage": { [key: string]: string }; "referenceSpan": { "from": string; "to": string; [key: string]: unknown }; "deltaT": [{ "model": "iers-utc/1"; "table": string; "tableDigest": string; [key: string]: unknown }, { "model": "zodiacs-deltat/1"; "table": string; "tableDigest": string; [key: string]: unknown }]; "timeResolution"?: { "resolver": string; "policy": { "fold"?: "earlier"; "gap"?: "shift-forward"; [key: string]: unknown }; "pinnedTzdb": { [key: string]: unknown }; "runtimeTzdb": (string | null); [key: string]: unknown }; "search"?: { "solver": "engine-longitude-crossings"; "stepDays": { [key: string]: number }; "bisections": number; "samples": number; "maxSamples": number; "window": "start-exclusive-end-inclusive"; "completeness": "tested-not-proven"; [key: string]: unknown }; "electionSearch"?: { "solver": "engine-longitude-crossings-and-sampled-houses"; "stepDays": { [key: string]: number }; "voidOfCourse": { "convention": "last-exact-ptolemaic-aspect-to-sign-exit"; "bodies": "modern"; "scanHours": number; [key: string]: unknown }; "houseSampleMinutes": 60; "boundarySeconds": 1; "resolutionSeconds": 2; "fullCalculationCost": 25; "samples": number; "maxSamples": number; "window": "start-inclusive-end-exclusive"; "completeness": "tested-not-proven"; [key: string]: unknown }; [key: string]: unknown };
"HousesResponse": { "schema": "zodiacs.compute-api.houses.v1"; "result": ComputeSchemas["HousesResult"]; "receipt": ComputeSchemas["CalculationReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"HousesResult": { "instant": string; "local": (ComputeSchemas["LocalResolution"] | null); "angles": (ComputeSchemas["Angles"] | null); "houses": (ComputeSchemas["Houses"] | null); "flags": Array<ComputeSchemas["ChartFlag"]>; "deltaT": ComputeSchemas["DeltaT"]; "timeScale": ComputeSchemas["TimeScale"]; [key: string]: unknown };
"EventsRequest": { "from": ComputeSchemas["Instant"]; "to": ComputeSchemas["Instant"]; "bodies"?: Array<"Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto">; "kinds"?: Array<"ingress" | "station" | "lunation"> };
"EventsResponse": { "schema": "zodiacs.compute-api.events.v1"; "result": ComputeSchemas["EventsResult"]; "receipt": ComputeSchemas["ComputeReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"EventsResult": { "from": string; "to": string; "events": Array<({ "kind": "ingress"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "at": string; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "retrograde": boolean; [key: string]: unknown } | { "kind": "station"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "at": string; "type": "retrograde" | "direct"; "lon": number; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; [key: string]: unknown } | { "kind": "lunation"; "type": "new" | "full"; "at": string; "lon": number; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; [key: string]: unknown })>; [key: string]: unknown };
"TimeRequest": { "local": ComputeSchemas["LocalTime"]; "longitude"?: ComputeSchemas["Longitude"] };
"TimeResponse": { "schema": "zodiacs.compute-api.time.v1"; "result": ComputeSchemas["TimeResult"]; "receipt": ComputeSchemas["ComputeReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"TimeResult": { "utc": string; "offsetMinutes": number; "flags": Array<"dst-gap" | "dst-fold" | "lmt" | "outside-reference-span">; "localMeanTime": ({ "longitude": number; "zoneOffsetMinutes": number; [key: string]: unknown } | null); "zoneHistory": "pinned" | "runtime"; "zoneUncertain": boolean; "tt": string; "deltaT": ComputeSchemas["DeltaT"]; "timeScale": ComputeSchemas["TimeScale"]; [key: string]: unknown };
"SkyFactRequest": (ComputeSchemas["SignFact"] | ComputeSchemas["RetrogradeFact"] | ComputeSchemas["IngressFact"] | ComputeSchemas["PhaseFact"]);
"SignFact": ({ "kind": "sign"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "instant"?: ComputeSchemas["Instant"]; "date"?: string; "zone"?: string }) & ({ "instant": unknown } | { "date": unknown });
"RetrogradeFact": ({ "kind": "retrograde"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "instant"?: ComputeSchemas["Instant"]; "date"?: string; "zone"?: string }) & ({ "instant": unknown } | { "date": unknown });
"IngressFact": { "kind": "ingress"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "date": string; "zone"?: string };
"PhaseFact": { "kind": "phase"; "phase": "new" | "first-quarter" | "full" | "last-quarter"; "date": string; "zone"?: string };
"SkyFactResponse": { "schema": "zodiacs.compute-api.sky-fact.v1"; "result": ComputeSchemas["SkyFactResult"]; "receipt": ComputeSchemas["ComputeReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"SkyFactResult": { "answer": "true" | "false" | "depends"; "basis": "instant" | "local-day" | "any-zone-day"; "fact": ComputeSchemas["SkyFactEcho"]; "instant": (string | null); "window": ({ "from": string; "to": string; [key: string]: unknown } | null); "zone": ({ "start": ComputeSchemas["ZoneEdge"]; "end": ComputeSchemas["ZoneEdge"]; [key: string]: unknown } | null); "facts": ({ "lon": number; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; "speed": number; "retrograde": boolean; "deltaT": ComputeSchemas["DeltaT"]; "timeScale": ComputeSchemas["TimeScale"]; "boundaryMarginArcsec"?: number; "flags": Array<"outside-reference-span">; [key: string]: unknown } | { "atStart": ComputeSchemas["BodyState"]; "atEnd": ComputeSchemas["BodyState"]; "flags": Array<"outside-reference-span">; "changes": Array<{ "at": string; "into": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "retrograde": boolean; [key: string]: unknown }>; [key: string]: unknown } | { "atStart": ComputeSchemas["BodyState"]; "atEnd": ComputeSchemas["BodyState"]; "flags": Array<"outside-reference-span">; "stations": Array<{ "at": string; "type": "retrograde" | "direct"; [key: string]: unknown }>; [key: string]: unknown } | { "ingresses": Array<{ "at": string; "retrograde": boolean; [key: string]: unknown }>; "flags": Array<"outside-reference-span">; [key: string]: unknown } | { "lunations": Array<{ "at": string; "lon": number; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; [key: string]: unknown }>; "flags": Array<"outside-reference-span">; [key: string]: unknown }); [key: string]: unknown };
"SkyFactEcho": { "kind": "sign" | "retrograde" | "ingress" | "phase"; "body"?: "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "sign"?: "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "phase"?: "new" | "first-quarter" | "full" | "last-quarter"; "instant"?: (string | null); "date": (string | null); "zone": (string | null); [key: string]: unknown };
"ZoneEdge": (ComputeSchemas["LocalResolution"] & { "utc": string; [key: string]: unknown });
"BodyState": { "lon": number; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "degree": number; "speed": number; "retrograde": boolean; [key: string]: unknown };
"ElectionsRequest": { "from": ComputeSchemas["Instant"]; "to": ComputeSchemas["Instant"]; "conditions": Array<ComputeSchemas["ElectionCondition"]>; "place"?: ComputeSchemas["ElectionPlace"] };
"ElectionCondition": (ComputeSchemas["PhaseCondition"] | ComputeSchemas["VoidOfCourseCondition"] | ComputeSchemas["SignCondition"] | ComputeSchemas["RetrogradeCondition"] | ComputeSchemas["AngularCondition"]);
"PhaseCondition": { "kind": "phase"; "phase": "waxing" | "waning"; "not"?: boolean };
"VoidOfCourseCondition": { "kind": "void-of-course"; "not"?: boolean };
"SignCondition": { "kind": "sign"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "sign": "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "not"?: boolean };
"RetrogradeCondition": { "kind": "retrograde"; "body": "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "not"?: boolean };
"AngularCondition": { "kind": "angular"; "body": "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "not"?: boolean };
"ElectionPlace": { "latitude": number; "longitude": ComputeSchemas["Longitude"]; "houseSystem"?: ComputeSchemas["HouseSystem"] };
"ElectionsResponse": { "schema": "zodiacs.compute-api.elections.v1"; "result": ComputeSchemas["ElectionsResult"]; "receipt": ComputeSchemas["ComputeReceipt"]; "backend": ComputeSchemas["Backend"]; "cite": ComputeSchemas["Cite"]; [key: string]: unknown };
"ElectionsResult": { "from": string; "to": string; "conditions": Array<{ "kind": "phase" | "void-of-course" | "sign" | "retrograde" | "angular"; "phase"?: "waxing" | "waning"; "body"?: "Sun" | "Moon" | "Mercury" | "Venus" | "Mars" | "Jupiter" | "Saturn" | "Uranus" | "Neptune" | "Pluto"; "sign"?: "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces"; "not": boolean; [key: string]: unknown }>; "place": ({ "latitude": number; "longitude": number; "houseSystem": ComputeSchemas["HouseSystem"]; [key: string]: unknown } | null); "windows": Array<{ "from": string; "to": string; [key: string]: unknown }>; "flags": Array<"outside-reference-span">; [key: string]: unknown };
}
export interface ComputeOperations {
"chart": { request: ComputeSchemas["PlaceInstantRequest"]; response: ComputeSchemas["ChartResponse"] };
"positions": { request: ComputeSchemas["PositionsRequest"]; response: ComputeSchemas["PositionsResponse"] };
"houses": { request: ComputeSchemas["PlaceInstantRequest"]; response: ComputeSchemas["HousesResponse"] };
"events": { request: ComputeSchemas["EventsRequest"]; response: ComputeSchemas["EventsResponse"] };
"time": { request: ComputeSchemas["TimeRequest"]; response: ComputeSchemas["TimeResponse"] };
"sky-fact": { request: ComputeSchemas["SkyFactRequest"]; response: ComputeSchemas["SkyFactResponse"] };
"elections": { request: ComputeSchemas["ElectionsRequest"]; response: ComputeSchemas["ElectionsResponse"] };
}
export const RESPONSE_SCHEMAS = {
"chart": "zodiacs.compute-api.chart.v1",
"positions": "zodiacs.compute-api.positions.v1",
"houses": "zodiacs.compute-api.houses.v1",
"events": "zodiacs.compute-api.events.v1",
"time": "zodiacs.compute-api.time.v1",
"sky-fact": "zodiacs.compute-api.sky-fact.v1",
"elections": "zodiacs.compute-api.elections.v1",
} as const;
