// The shipped zone histories before 1970 (src/tzdb/, generated by
// scripts/build-tz-shards.mjs from tzdata 2025c with backzone), loaded one
// bucket at a time on request, and the default build's causes from 1970 on.
import { LATER_CAUSES, SHARD_LOADERS, TZDB } from "../tzdb/tzdb-2025c.js";

export { TZDB };

/** One generated shard entry; see scripts/build-tz-shards.mjs. */
export interface ZoneShard {
  n: string;
  s: string;
  h?: 1;
  f: number | null;
  e?: [number, number][];
  y: [number | null, number, string][];
  t: string;
  k: string;
}
export type ZoneShardBucket = Record<string, ZoneShard>;

/** What changed at a transition, from the tzdb record. */
export type TransitionCause = "dst" | "legal-change" | "date-line";

const CAUSES: Readonly<Record<string, TransitionCause>> = { d: "dst", l: "legal-change", x: "date-line" };

/** One zone name's history before 1970, decoded. Instants in ms, offsets in seconds east. */
export interface ZoneHistory {
  name: string;
  /** The tzdb zone the name resolves to. */
  source: string;
  /** The history is the default build's (tzdb's main form), not backzone's. */
  hostLegal: boolean;
  /** When the zone's own clock left local mean time, or null. */
  zoneEraEnd: number | null;
  /** Backzone's local mean time era, [until, offset] per line (more than one across the date line). */
  era: readonly (readonly [number, number])[] | null;
  times: readonly number[];
  /** Index into the type arrays: the type before the first transition, then after each. */
  types: readonly number[];
  causes: readonly TransitionCause[];
  offsets: readonly (number | null)[];
  dst: readonly boolean[];
  abbreviations: readonly string[];
}

/** 32-bit FNV-1a of the lower-cased name, as the generator computes it. */
export function nameHash(name: string): number {
  const key = name.toLowerCase();
  let hash = 0x811c9dc5;
  for (let index = 0; index < key.length; index += 1) {
    hash ^= key.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash;
}

function decode(entry: ZoneShard): ZoneHistory {
  const times: number[] = [];
  let previous = 0;
  if (entry.t) {
    entry.t.split(",").forEach((part, index) => {
      const value = parseInt(part, 36);
      previous = index === 0 ? value : previous + value;
      times.push(previous * 1000);
    });
  }
  const types = [0];
  const causes: TransitionCause[] = [];
  for (let index = 0; index < entry.k.length; index += 2) {
    types.push(parseInt(entry.k[index]!, 36));
    causes.push(CAUSES[entry.k[index + 1]!]!);
  }
  return {
    name: entry.n,
    source: entry.s,
    hostLegal: entry.h === 1,
    zoneEraEnd: entry.f === null ? null : entry.f * 1000,
    era: entry.e ? entry.e.map(([until, offset]) => [until * 1000, offset] as const) : null,
    times,
    types,
    causes,
    offsets: entry.y.map((type) => type[0]),
    dst: entry.y.map((type) => type[1] === 1),
    abbreviations: entry.y.map((type) => type[2])
  };
}

/** Loaded histories by lower-cased name; null where the release has no such name. */
const histories = new Map<string, ZoneHistory | null>();
const loads = new Map<number, Promise<ZoneShardBucket>>();

/** The loaded history of a name: undefined until loaded, null when the release lacks it. */
export function loadedHistory(timeZone: string): ZoneHistory | null | undefined {
  return histories.get(timeZone.toLowerCase());
}

/**
 * Load a name's history. A failed load is not remembered, so a later call
 * tries again; a caller that stops waiting leaves no unhandled rejection.
 */
export function loadHistory(timeZone: string): Promise<void> {
  const key = timeZone.toLowerCase();
  if (histories.has(key)) return Promise.resolve();
  const bucket = nameHash(timeZone) % SHARD_LOADERS.length;
  let pending = loads.get(bucket);
  if (!pending) {
    const load = SHARD_LOADERS[bucket]!().then((module) => module.default);
    loads.set(bucket, load);
    void load.catch(() => {
      if (loads.get(bucket) === load) loads.delete(bucket);
    });
    pending = load;
  }
  const ready = pending.then((zones) => {
    const entry = Object.prototype.hasOwnProperty.call(zones, key) ? zones[key] : undefined;
    histories.set(key, entry ? decode(entry) : null);
  });
  void ready.catch(() => {});
  return ready;
}

/** Index of the type in force at an instant. */
export function typeIndexAt(history: ZoneHistory, ms: number): number {
  let lo = 0;
  let hi = history.times.length;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (history.times[mid]! <= ms) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

/** The recorded transition at exactly this instant, as its index, or -1. */
export function transitionAt(history: ZoneHistory, ms: number): number {
  const index = typeIndexAt(history, ms) - 1;
  return index >= 0 && history.times[index] === ms ? index : -1;
}

let later: Map<number, Map<number, TransitionCause>> | undefined;

/** The default build's cause for a transition from 1970 on: legal change or date line when recorded, otherwise daylight saving. */
export function laterCause(timeZone: string, ms: number): TransitionCause {
  if (!later) {
    later = new Map();
    for (const row of LATER_CAUSES.split(";")) {
      const causes = new Map<number, TransitionCause>();
      let at = 0;
      for (const [, digits, mark] of row.slice(5).matchAll(/([0-9a-z]+)([.!_~])/g)) {
        const kind = ".!_~".indexOf(mark!);
        at += parseInt(digits!, 36) * (kind < 2 ? 60_000 : 1000);
        causes.set(at, kind % 2 ? "date-line" : "legal-change");
      }
      later.set(parseInt(row.slice(0, 5), 36), causes);
    }
  }
  return later.get(nameHash(timeZone) % 36 ** 5)?.get(ms) ?? "dst";
}
