/**
 * Parity with the Zodiacs.org site code these techniques were ported from.
 * The inputs come from scripts/techniques-parity-corpus.mjs; the site's
 * outputs were generated by docs/evidence/techniques-2026-09-29/site-parity.mjs
 * (site commit 67cccac5) and are kept in fixtures/site-parity/. The site's code
 * runs on the engine it is given, so they were generated again on this tree's
 * packed build when the engine took the full IAU 2000B nutation, which moves
 * the site's returns and void-of-course windows as it moves the package's
 * (docs/evidence/rc16-20260930). Every corpus must agree exactly, except where the
 * preregistration (docs/evidence/techniques-2026-09-29/PREREGISTRATION.md)
 * records a difference by design; those cases are pinned here one by one.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  checkComposite,
  checkDignities,
  checkMoonSigns,
  checkPatterns,
  checkReturns,
  checkVoidOfCourse
} from "../../scripts/techniques-parity-check.mjs";
import { matchAspect } from "../aspects.js";
import { bodyLongitude } from "../ephemeris.js";
import { prepareLocalTime } from "../geo/timezone.js";
import * as techniques from "../techniques.js";

const fixture = (name: string) =>
  JSON.parse(readFileSync(new URL(`./fixtures/site-parity/${name}.json`, import.meta.url), "utf8"));
const api = { ...techniques, bodyLongitude, matchAspect };

describe("parity with the site's code", () => {
  it("returns: every instant and chart of R-SI, R-SM, R-SC, R-LI and R-LC", () => {
    const results = checkReturns(api, fixture("returns"));
    for (const result of results.filter((row) => row.corpus !== "R-E")) {
      expect(result.disagreements, result.corpus).toEqual([]);
      expect(result.cases, result.corpus).toBeGreaterThanOrEqual(60);
    }
    // R-E: the site clips its scans to 1800–2200 and refuses beyond; the
    // package does not clip. Where the site gave an answer from a clipped
    // window, the package finds the same return from its own window, within
    // the solver's resolution (a 1-day step / 2^24, about 5 ms).
    const edge = results.find((row) => row.corpus === "R-E")!;
    for (const row of edge.disagreements) {
      if (typeof row.site === "number") expect(Math.abs(row.site - row.package)).toBeLessThanOrEqual(6);
      else expect(row.site).toHaveProperty("error");
    }
  }, 120_000);

  it("composite midpoints and aspects", () => {
    for (const result of checkComposite(api, fixture("composite"))) expect(result.disagreements, result.corpus).toEqual([]);
  });

  it("void-of-course windows and status", () => {
    for (const result of checkVoidOfCourse(api, fixture("void-of-course"))) expect(result.disagreements, result.corpus).toEqual([]);
  }, 120_000);

  it("aspect patterns and their containment", () => {
    for (const result of checkPatterns(api, fixture("aspect-patterns"))) expect(result.disagreements, result.corpus).toEqual([]);
  });

  it("dignities of every body in every sign", () => {
    for (const result of checkDignities(api, fixture("dignities"))) expect(result.disagreements, result.corpus).toEqual([]);
  });

  it("Moon signs over a date", async () => {
    const expected = fixture("moon-sign");
    // The local midnights come from the host's Intl data after 1970; they are
    // compared on the tzdata the site's outputs were generated with.
    const compareMidnights = process.versions.tz === expected.meta.tz;
    const results = await checkMoonSigns(api, expected, { compareMidnights, prepare: prepareLocalTime });
    const byName = (name: string) => results.find((row) => row.corpus === name)!;
    expect(byName("M-A").disagreements).toEqual([]);
    // Pacific/Apia skipped 2011-12-30. The site takes the Moon's sign at its
    // midnights 1 ms apart, the package refuses the date: the one difference.
    for (const name of ["M-Z (signs over the site's endpoints)", ...(compareMidnights ? ["M-Z"] : [])]) {
      const rows = byName(name).disagreements;
      expect(rows.map((row: { package: unknown }) => row.package), name).toEqual([{ error: expect.stringMatching(/^RangeError/u) }]);
      expect(rows.map((row: { index: number }) => row.index), name).toEqual([1500 + 7 * 3 + 1]);
    }
    // M-P (before 1970): the site reads midnights on the host's Intl data, the
    // package on its tzdata 2025c with backzone. Every disagreement is a
    // different midnight at one end or the other (G7).
    for (const row of byName("M-P").disagreements) {
      expect(Array.isArray(row.site) && Array.isArray(row.package)).toBe(true);
      expect(row.site[0] !== row.package[0] || row.site[1] !== row.package[1]).toBe(true);
    }
  }, 120_000);
});
