import net from 'node:net';
import http from 'node:http';
import https from 'node:https';
import { syncBuiltinESMExports } from 'node:module';
const denied = () => { throw new Error('Offline consumer refused a network request'); };
globalThis.fetch = denied;
globalThis.WebSocket = denied;
net.connect = denied;
net.createConnection = denied;
net.Socket.prototype.connect = denied;
http.request = denied;
http.get = denied;
https.request = denied;
https.get = denied;
syncBuiltinESMExports();
