#!/usr/bin/env node
/*
 * Write RESULTS.md and results/summary.json from the vector files and the
 * committed results files.
 *
 *   node conformance/harness/report.mjs           write both
 *   node conformance/harness/report.mjs --check   fail if either is stale
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { KINDS, LEVEL_FILES, SUITE, SUITE_DIR, SUITE_VERSION, readSuite } from './lib.mjs';

const RESULTS_DIR = resolve(SUITE_DIR, 'results');
const RUN_ORDER = ['zodiacs-engine.json', 'pyswisseph.json'];
const SYMBOL = { arcsec: '″', deg: '°', s: ' s' };

function describeRule(rule) {
  if (rule.exact) return 'exact';
  if (rule.each) return `each ${describeRule(rule.each)}`;
  return `±${rule.abs}${SYMBOL[rule.unit]}${rule.wrap ? ' (on the circle)' : ''}`;
}

const describeTolerance = (tolerance) => Object.entries(tolerance).map(([field, rule]) => `${field} ${describeRule(rule)}`).join('; ');

function levels(suite) {
  return suite.map(({ level, file, digest }) => {
    const kinds = [];
    for (const kind of Object.keys(KINDS).filter((name) => KINDS[name].level === level)) {
      const vectors = file.vectors.filter((vector) => vector.kind === kind);
      if (!vectors.length) continue;
      const tolerances = [...new Set(vectors.map((vector) => describeTolerance(vector.tolerance)))];
      kinds.push({ kind, count: vectors.length, tolerance: tolerances.join(', or ') });
    }
    return {
      level,
      title: file.title,
      file: LEVEL_FILES[level],
      sha256: digest,
      count: file.vectors.length,
      kinds,
      arbiters: Object.entries(file.arbiters).map(([id, arbiter]) => ({ id, name: arbiter.name, source: arbiter.source, uncertainty: arbiter.uncertainty })),
    };
  });
}

function runs() {
  if (!existsSync(RESULTS_DIR)) return [];
  const names = readdirSync(RESULTS_DIR).filter((name) => name.endsWith('.json') && name !== 'summary.json');
  names.sort((a, b) => (RUN_ORDER.indexOf(a) + 1 || 99) - (RUN_ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b));
  return names.map((name) => {
    const document = JSON.parse(readFileSync(resolve(RESULTS_DIR, name), 'utf8'));
    const notesPath = resolve(RESULTS_DIR, name.replace(/\.json$/u, '.notes.md'));
    const notes = existsSync(notesPath) ? readFileSync(notesPath, 'utf8').trim() : null;
    return { file: `results/${name}`, adapter: document.adapter, values: document.values, vectors: document.vectors, summary: document.summary, notes };
  });
}

const count = (bucket) => `${bucket.pass} | ${bucket.fail} | ${bucket.unsupported} | ${bucket.error}`;

function residualText(kindSummary) {
  const parts = Object.entries(kindSummary.residuals ?? {}).map(([field, stats]) => {
    const unit = SYMBOL[stats.unit];
    const format = (value) => (stats.unit === 'arcsec' ? value.toFixed(3) : value.toPrecision(3));
    return `${field}: ${format(stats.median)}${unit} / ${format(stats.p95)}${unit} / ${format(stats.max)}${unit}`;
  });
  return parts.join('<br>') || '—';
}

function markdown(summary) {
  const out = [];
  out.push('# Conformance results');
  out.push('');
  out.push('Generated by `node conformance/harness/report.mjs` from the vector files and `results/*.json`; do not edit by hand.');
  out.push('');
  const total = summary.levels.reduce((sum, level) => sum + level.count, 0);
  out.push(`Suite ${summary.suiteVersion}: ${total} vectors (${summary.levels.map((level) => `${level.level} ${level.count}`).join(', ')}). Each vector names its arbiter and tolerance; see [README.md](README.md) and [SPEC.md](SPEC.md).`);
  out.push('');
  out.push('## Vectors');
  out.push('');
  out.push('| level | kind | vectors | tolerance |');
  out.push('| --- | --- | ---: | --- |');
  for (const level of summary.levels) {
    for (const kind of level.kinds) out.push(`| ${level.level} | \`${kind.kind}\` | ${kind.count} | ${kind.tolerance.replace(/\|/gu, '\\|')} |`);
  }
  out.push('');
  for (const run of summary.runs) {
    const adapter = run.adapter;
    out.push(`## ${adapter.engine} ${adapter.engineVersion}`);
    out.push('');
    out.push(`Adapter \`${adapter.name}\` ${adapter.version}; results in [\`${run.file}\`](${run.file})${run.values === 'none' ? ' (verdicts and statistics only)' : ''}.`);
    const stale = Object.entries(run.vectors).filter(([file, digest]) => summary.levels.find((level) => level.file === file)?.sha256 !== digest);
    if (stale.length) out.push(`**These results were computed on an earlier version of ${stale.map(([file]) => file).join(', ')}.**`);
    out.push('');
    out.push('| configuration | |');
    out.push('| --- | --- |');
    for (const [key, value] of Object.entries(adapter.configuration ?? {})) {
      const text = typeof value === 'string' ? value : Object.entries(value).map(([k, v]) => `${k} ${String(v).slice(0, 12)}…`).join(', ');
      out.push(`| ${key} | ${text.replace(/\|/gu, '\\|')} |`);
    }
    out.push('');
    out.push('| level | kind | pass | fail | unsupported | error | residual median / 95th percentile / max |');
    out.push('| --- | --- | ---: | ---: | ---: | ---: | --- |');
    for (const level of summary.levels) {
      for (const kind of level.kinds) {
        const bucket = run.summary.byKind[kind.kind];
        if (bucket) out.push(`| ${level.level} | \`${kind.kind}\` | ${count(bucket)} | ${residualText(bucket)} |`);
      }
      const bucket = run.summary.byLevel[level.level];
      if (bucket) out.push(`| **${level.level}** | **all** | **${bucket.pass}** | **${bucket.fail}** | **${bucket.unsupported}** | **${bucket.error}** | |`);
    }
    out.push('');
    const tags = Object.entries(run.summary.byTag ?? {});
    if (tags.length) {
      out.push('| vectors tagged | pass | fail | unsupported | error |');
      out.push('| --- | ---: | ---: | ---: | ---: |');
      for (const [tag, bucket] of tags) out.push(`| \`${tag}\` | ${count(bucket)} |`);
      out.push('');
    }
    if (run.notes) {
      out.push(run.notes);
      out.push('');
    }
  }
  return `${out.join('\n')}\n`;
}

const suite = readSuite();
const summary = { suite: SUITE, suiteVersion: SUITE_VERSION, levels: levels(suite), runs: runs() };
const json = `${JSON.stringify(summary, null, 2)}\n`;
const md = markdown(summary);
const targets = [[resolve(RESULTS_DIR, 'summary.json'), json], [resolve(SUITE_DIR, 'RESULTS.md'), md]];

if (process.argv.includes('--check')) {
  const stale = targets.filter(([path, text]) => !existsSync(path) || readFileSync(path, 'utf8') !== text).map(([path]) => path);
  if (stale.length) {
    console.error(`conformance: stale, run node conformance/harness/report.mjs:\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('conformance: RESULTS.md and results/summary.json are current');
} else {
  for (const [path, text] of targets) writeFileSync(path, text);
  console.log('conformance: wrote RESULTS.md and results/summary.json');
}
